language: java
jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
